export const mockMovies = {
    "movies": {
        "Top Rated": [
            {
                "movie_id": 38,
                "title": "Spirited Away",
                "release_date": "2001-07-20",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://images-testing-temp.s3.eu-west-3.amazonaws.com/req.user.id/Screenshot%202024-12-07%20at%2018.58.16.png",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//hZth9NCeXvvO7Xi98d8q34e1Ier.jpg",
                "overview": "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
                "creation_date": null
            },
            {
                "movie_id": 48,
                "title": "The Good, the Bad and the Ugly",
                "release_date": "1966-12-23",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
                "overview": "While the Civil War rages between the Union and the Confederacy, three men – a quiet loner, a ruthless hit man and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
                "creation_date": null
            },
            {
                "movie_id": 49,
                "title": "Pulp Fiction",
                "release_date": "1994-09-10",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
                "overview": "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
                "creation_date": null
            },
            {
                "movie_id": 47,
                "title": "Gabriel's Inferno: Part II",
                "release_date": "2020-07-31",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
                "overview": "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
                "creation_date": null
            },
            {
                "movie_id": 33,
                "title": "Dilwale Dulhania Le Jayenge",
                "release_date": "1995-10-19",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
                "overview": "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
                "creation_date": null
            },
            {
                "movie_id": 34,
                "title": "The Shawshank Redemption",
                "release_date": "1994-09-23",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
                "overview": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
                "creation_date": null
            },
            {
                "movie_id": 35,
                "title": "The Godfather",
                "release_date": "1972-03-14",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
                "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
                "creation_date": null
            },
            {
                "movie_id": 45,
                "title": "The Green Mile",
                "release_date": "1999-12-10",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//velWPhVMQeQKcxggNEU8YmIo52R.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
                "overview": "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
                "creation_date": null
            },
            {
                "movie_id": 39,
                "title": "Schindler's List",
                "release_date": "1993-12-15",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
                "overview": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
                "creation_date": null
            },
            {
                "movie_id": 36,
                "title": "Impossible Things",
                "release_date": "2021-06-17",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//bxSBOAD8AuMHYMdW3jso9npAkgt.jpg",
                "overview": "Matilde is a woman who, after the death of her husband - a man who constantly abused her - finds her new best friend in Miguel, her young, insecure, disoriented and even dealer neighbor",
                "creation_date": null
            },
            {
                "movie_id": 31,
                "title": "The Godfather: Part II",
                "release_date": "1974-12-20",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
                "overview": "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
                "creation_date": null
            },
            {
                "movie_id": 50,
                "title": "The Lord of the Rings: The Return of the King",
                "release_date": "2003-12-01",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//pm0RiwNpSja8gR0BTWpxo5a9Bbl.jpg",
                "overview": "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
                "creation_date": null
            },
            {
                "movie_id": 44,
                "title": "Parasite",
                "release_date": "2019-05-30",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
                "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
                "creation_date": null
            },
            {
                "movie_id": 42,
                "title": "12 Angry Men",
                "release_date": "1957-04-10",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//tj6iPnz18hGfr0LKqWmG6Cp3niO.jpg",
                "overview": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
                "creation_date": null
            },
            {
                "movie_id": 41,
                "title": "Your Name.",
                "release_date": "2016-08-26",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//q719jXXEzOoYaps6babgKnONONX.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg",
                "overview": "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
                "creation_date": null
            },
            {
                "movie_id": 46,
                "title": "The Dark Knight",
                "release_date": "2008-07-14",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
                "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
                "creation_date": null
            },
            {
                "movie_id": 40,
                "title": "Dou kyu sei – Classmates",
                "release_date": "2016-02-20",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//cIfRCA5wEvj9tApca4UDUagQEiM.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg",
                "overview": "Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.",
                "creation_date": null
            },
            {
                "movie_id": 43,
                "title": "Gabriel's Inferno",
                "release_date": "2020-05-29",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
                "overview": "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
                "creation_date": null
            },
            {
                "movie_id": 32,
                "title": "Your Eyes Tell",
                "release_date": "2020-10-23",
                "author": "temp",
                "type": "Top Rated",
                "poster": "https://image.tmdb.org/t/p/original//cVn8E3Fxbi8HzYYtaSfsblYC4gl.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//v5CEt88iDsuoMaW1Q5Msu9UZdEt.jpg",
                "overview": "A tragic accident lead to Kaori's blindness, but she clings to life and the smaller pleasures it can still afford her. She meets Rui and begins to talk to him. Rui was once a promising kickboxer, but something happened in his past. Kaori's smile brings out a change in Rui. However, the two are connected in more than one way. Rui attempts to do what is right.",
                "creation_date": null
            }
        ],
        "Trending": [
            {
                "movie_id": 15,
                "title": "Lightyear",
                "release_date": "2022-06-15",
                "author": "temp",
                "type": "Trending",
                "poster": "https://temporary-images-epita.s3.amazonaws.com/6676938536e4b8d21afe1aa3/Screenshot%202024-06-22%20at%2016.33.38.png",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//nW5fUbldp1DYf2uQ3zJTUdachOu.jpg",
                "overview": "Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.",
                "creation_date": null
            },
            {
                "movie_id": 26,
                "title": "Everything Everywhere All at Once",
                "release_date": "2022-03-24",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg",
                "overview": "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
                "creation_date": null
            },
            {
                "movie_id": 24,
                "title": "Purple Hearts",
                "release_date": "2022-07-29",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//4JyNWkryifWbWXJyxcWh3pVya6N.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//k5SYb9AM0x4IGVxG8fYEEH4wK1I.jpg",
                "overview": "An aspiring musician agrees to a marriage of convenience with a soon-to-deploy Marine, but a tragedy soon turns their fake relationship all too real.",
                "creation_date": null
            },
            {
                "movie_id": 19,
                "title": "The Gray Man",
                "release_date": "2022-07-13",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//8cXbitsS6dWQ5gfMTZdorpAAzEH.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//27Mj3rFYP3xqFy7lnz17vEd8Ms.jpg",
                "overview": "When a shadowy CIA agent uncovers damning agency secrets, he's hunted across the globe by a sociopathic rogue operative who's put a bounty on his head.",
                "creation_date": null
            },
            {
                "movie_id": 25,
                "title": "The Black Phone",
                "release_date": "2022-06-22",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//p9ZUzCyy9wRTDuuQexkQ78R2BgF.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
                "overview": "Finney Shaw, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.",
                "creation_date": null
            },
            {
                "movie_id": 30,
                "title": "Carter",
                "release_date": "2022-08-05",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//uzAh3Ub2YttCz13cnyB9PvhpmIL.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//gt7ekbyM4q6N8aAZN0Oct3xY8tm.jpg",
                "overview": "A man wakes up missing his memories. Directed by a mysterious voice from a device in his ear, he sets off on a hostage rescue mission rife with danger.",
                "creation_date": null
            },
            {
                "movie_id": 21,
                "title": "Thor: Love and Thunder",
                "release_date": "2022-07-06",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//p1F51Lvj3sMopG948F5HsBbl43C.jpg",
                "overview": "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
                "creation_date": null
            },
            {
                "movie_id": 17,
                "title": "Prey",
                "release_date": "2022-07-21",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//cv6zBbPfP0MMxgMdve95YrIIQwq.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg",
                "overview": "In the Comanche Nation in 1717, a fierce and highly skilled warrior named Naru learns the prey she is stalking is a highly evolved alien with a technologically advanced arsenal.",
                "creation_date": null
            },
            {
                "movie_id": 28,
                "title": "Bullet Train",
                "release_date": "2022-07-03",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//C8FpZfTPEZDjngPlatiFsaDB4A.jpg",
                "overview": "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
                "creation_date": null
            },
            {
                "movie_id": 20,
                "title": "Jurassic World Dominion",
                "release_date": "2022-06-01",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//9eAn20y26wtB3aet7w9lHjuSgZ3.jpg",
                "overview": "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
                "creation_date": null
            },
            {
                "movie_id": 18,
                "title": "Minions: The Rise of Gru",
                "release_date": "2022-06-29",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//bX55XT5HEOkULrKli8MIXbcuaJF.jpg",
                "overview": "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
                "creation_date": null
            },
            {
                "movie_id": 27,
                "title": "Top Gun: Maverick",
                "release_date": "2022-05-24",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
                "overview": "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
                "creation_date": null
            },
            {
                "movie_id": 23,
                "title": "Thirteen Lives",
                "release_date": "2022-07-18",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//yi5KcJqFxy0D6yP8nCfcF8gJGg5.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//tLXdaL1yNnHtHFYrL1RAKwt7nPx.jpg",
                "overview": "Based on the true nail-biting mission that captivated the world. Twelve boys and the coach of a Thai soccer team explore the Tham Luang cave when an unexpected rainstorm traps them in a chamber inside the mountain. Entombed behind a maze of flooded cave tunnels, they face impossible odds. A team of world-class divers navigate through miles of dangerous cave networks to discover that finding the boys is only the beginning.",
                "creation_date": null
            },
            {
                "movie_id": 29,
                "title": "Spider-Man: No Way Home",
                "release_date": "2021-12-15",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg",
                "overview": "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
                "creation_date": null
            },
            {
                "movie_id": 22,
                "title": "Doctor Strange in the Multiverse of Madness",
                "release_date": "2022-05-04",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
                "overview": "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
                "creation_date": null
            },
            {
                "movie_id": 16,
                "title": "Luck",
                "release_date": "2022-08-05",
                "author": "temp",
                "type": "Trending",
                "poster": "https://image.tmdb.org/t/p/original//1HOYvwGFioUFL58UVvDRG6beEDm.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//sKvQUSyqsFq8e1ts6oo3Xp3dPH2.jpg",
                "overview": "Suddenly finding herself in the never-before-seen Land of Luck, the unluckiest person in the world must unite with the magical creatures there to turn her luck around.",
                "creation_date": null
            }
        ],
        "Horror": [
            {
                "movie_id": 79,
                "title": "The Jack in the Box: Awakening",
                "release_date": "2022-02-24",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//3Ib8vlWTrAKRrTWUrTrZPOMW4jp.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//xHRabofjmMGoIV3mb6xgy4nwOcS.jpg",
                "overview": "When a vintage Jack-in-the-box is opened by a dying woman, she enters into a deal with the demon within that would see her illness cured in return for helping it claim six innocent victims.",
                "creation_date": null
            },
            {
                "movie_id": 217,
                "title": "No Exit",
                "release_date": "2022-02-25",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//5cnLoWq9o5tuLe1Zq4BTX4LwZ2B.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//2il2HT8v6NAN7oinOCuHKpEhgnB.jpg",
                "overview": "Stranded at a rest stop in the mountains during a blizzard, a recovering addict discovers a kidnapped child hidden in a car belonging to one of the people inside the building which sets her on a terrifying struggle to identify who among them is the kidnapper.",
                "creation_date": null
            },
            {
                "movie_id": 77,
                "title": "The Passenger",
                "release_date": "2022-06-03",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//6bYCDIYqT3GpE6ICnMP6HvUlJMT.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//9hhRzLzP1enjENXiGJocAHyWFmS.jpg",
                "overview": "Four people traveling in a van run over a lone woman while she is walking in the dark down a country road. After loading her into the vehicle to take her to the nearest hospital, they notice that she is behaving rather strangely. The occupants of the van soon realise that the time has come to fight for their lives, and together they agree on one very simple rule: \"do not sit next to her.\"",
                "creation_date": null
            },
            {
                "movie_id": 211,
                "title": "V for Vengeance",
                "release_date": "2022-06-07",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//jLtP8TLycVzLUlkkhp8PipXfUh6.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//zSDyqp2mhV45ZjI1EUBMfzupKKt.jpg",
                "overview": "After learning that their younger sibling escaped an earlier kidnapping attempt that also killed their parents, two estranged sisters must join forces to rescue her from a group of bloodthirsty vampires. Out for revenge and control of a vampirism vaccine, Thorn and his band of the undead soon learn that they messed with the wrong family.",
                "creation_date": null
            },
            {
                "movie_id": 212,
                "title": "The Grandmother",
                "release_date": "2022-01-28",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//eIUixNvox4U4foL5Z9KbN9HXYSM.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//An1nKjXahrChfEbZ3MAE8fsiut1.jpg",
                "overview": "A Paris model must return to Madrid where her grandmother, who raised her, has had a stroke. But spending just a few days with this relative turns into an unexpected nightmare.",
                "creation_date": null
            },
            {
                "movie_id": 215,
                "title": "Resident Evil: Welcome to Raccoon City",
                "release_date": "2021-11-24",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//o76ZDm8PS9791XiuieNB93UZcRV.jpg",
                "overview": "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
                "creation_date": null
            },
            {
                "movie_id": 87,
                "title": "See for Me",
                "release_date": "2022-01-07",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//qk1ZERG6yhwAJqTobmDgw8jRL2C.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//tzNx4y7kYf1Xw3F3T6QxrE7PPwb.jpg",
                "overview": "When blind former skier Sophie cat-sits in a secluded mansion, three thieves invade for the hidden safe. Sophie's only defense is army veteran Kelly, who she meets on the See For Me app. Kelly helps Sophie defend herself against the invaders and survive.",
                "creation_date": null
            },
            {
                "movie_id": 74,
                "title": "Constantine: The House of Mystery",
                "release_date": "2022-05-02",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//kqYDoEb9PxLXM2ccoHInMMJalti.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//vsAlkb3Fv485AmNiSoyjEBcIB7B.jpg",
                "overview": "John Constantine wakes up in the eerie House of Mystery with no recollection of how he got there. Fortunately, Zatanna and his friends are all there. Unfortunately, they have a bad habit of turning into demons and ripping him to shreds, over and over again!",
                "creation_date": null
            },
            {
                "movie_id": 71,
                "title": "Shark Bait",
                "release_date": "2022-05-13",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//mVVU9zC8snNHlcqYONY2HOsh9ob.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//jVGHRpSgtE2MQLJhC5q4lXmPNQW.jpg",
                "overview": "A group of friends enjoying a weekend steal a couple of jetskis racing them out to sea, ending up in a horrific head-on collision. They struggle to find a way home with a badly injured friend while from the waters below predators lurk.",
                "creation_date": null
            },
            {
                "movie_id": 70,
                "title": "The Exorcism of God",
                "release_date": "2022-03-11",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//hangTmbxpSV4gpHG7MgSlCWSSFa.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//b1L7qevxiVpkVFq4dmdQPGFPWH0.jpg",
                "overview": "An American priest working in Mexico is considered a saint by many local parishioners. However, due to a botched exorcism, he carries a secret that’s eating him alive until he gets an opportunity to face his demon one final time.",
                "creation_date": null
            },
            {
                "movie_id": 216,
                "title": "Dark Cloud",
                "release_date": "2022-05-09",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//q1ngkvPCnOYKeyNZjg8QqvaSnuZ.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//qhRQLTYnGWvI4nYE05DaDjgvCna.jpg",
                "overview": "Following the aftermath of a horrific accident, a woman is voluntarily subjected to artificial intelligence for rehabilitation.",
                "creation_date": null
            },
            {
                "movie_id": 213,
                "title": "Titanic 666",
                "release_date": "2022-04-15",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//EX0ITg5YqDgFHjujpTNhEPaJSL.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//5DCIRgOrCTayoCGggVn1kyqs1Vh.jpg",
                "overview": "After a mammoth cruise ship sails over the site of the Titanic’s disaster, dark and deadly events start to occur on board. As the ship’s captain investigates the tragic occurrences, it becomes clear that the passengers and crew from the original Titanic have returned.",
                "creation_date": null
            },
            {
                "movie_id": 75,
                "title": "Incantation",
                "release_date": "2022-03-18",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//6zltP23zLGPogsHZUazSrrwNuKs.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//6d1mHKcozT5AaZeI76ehJrBt0hr.jpg",
                "overview": "Inspired by a true story of a family who believed they were possessed by spirits, this film follows a woman who must protect her child from a curse.  WARNING: This is a cursed video, it might contain certain risks to watch. For those who dares to follow, please solve the puzzle of my daughter's curse with me.",
                "creation_date": null
            },
            {
                "movie_id": 73,
                "title": "Shut In",
                "release_date": "2022-03-24",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//b5ug4LyLQFeR6azAJyIPBQz5ur9.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//zTffxrYeeKfDMuaIeabDjKTaSuX.jpg",
                "overview": "A young single mother is held captive along with her two children by a violent ex and must plot their escape before it’s too late.",
                "creation_date": null
            },
            {
                "movie_id": 214,
                "title": "Veneciafrenia",
                "release_date": "2022-04-22",
                "author": "temp",
                "type": "Horror",
                "poster": "https://image.tmdb.org/t/p/original//luMC56bwZqaECYRz6X7sXjqN6nd.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//egS5SHI4Ppwmb65lUjqsy79ASnN.jpg",
                "overview": "A group of spanish tourists in Venice finds themselves fighting for their lives against locals that are not too keen on foreigners.",
                "creation_date": null
            }
        ],
        "Romance": [
            {
                "movie_id": 226,
                "title": "After",
                "release_date": "2019-04-11",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//u3B2YKUjWABcxXZ6Nm9h10hLUbh.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//997ToEZvF2Obp9zNZbY5ELVnmrW.jpg",
                "overview": "Tessa Young is a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart. Entering her first semester of college, Tessa's guarded world opens up when she meets Hardin Scott, a mysterious and brooding rebel who makes her question all she thought she knew about herself -- and what she wants out of life.",
                "creation_date": null
            },
            {
                "movie_id": 95,
                "title": "Through My Window",
                "release_date": "2022-02-04",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//6gg7fvKc1ZxP9yCczweSxIGYp4S.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//4rsomWxlqnHt3muGYK06auhOib6.jpg",
                "overview": "Raquel's longtime crush on her next-door neighbor turns into something more when he starts developing feelings for her, despite his family's objections.",
                "creation_date": null
            },
            {
                "movie_id": 94,
                "title": "Hello, Goodbye, and Everything in Between",
                "release_date": "2022-07-06",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//xyGsnp4Ld5PmJYYWnfuYYoENhHt.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//8vn4eis4xk6cnOnAuAcyzPbqVb0.jpg",
                "overview": "Clare and Aidan, who after making a pact that they would break up before college, find themselves retracing the steps of their relationship on their last evening as a couple. The epic date leads them to familiar landmarks, unexpected places, and causes them to question whether high school love is meant to last.",
                "creation_date": null
            },
            {
                "movie_id": 218,
                "title": "I Don't Like Younger Men 5",
                "release_date": "2020-04-23",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//iyI4yY4bUtWS1demuvjfGj5Jclw.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//xiKwkUUmRTqqZJP4akBHgWnD6Hv.jpg",
                "overview": "Ha-neul haven't seen her friend, Ye-sol for a long time, and so they spent a good time together. That time, Ye-sol's father, Min-soo enters the house.  Ha-neul sees the young-looking Min-soo and makes a fuss. Ye-sol who is a little bit tipsy tells Ha-neul that he is her stepfather.  That night, Ha-neul secretly entered Min-soo's room...",
                "creation_date": null
            },
            {
                "movie_id": 91,
                "title": "365 Days: This Day",
                "release_date": "2022-04-27",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//7qU0SOVcQ8BTJLodcAlulUAG16C.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//oasoFPah6e5kKHXEWOUVVgDoIva.jpg",
                "overview": "Laura and Massimo are back and hotter than ever. But the reunited couple's new beginning is complicated by Massimo’s family ties and a mysterious man who enters Laura’s life to win her heart and trust, at any cost.",
                "creation_date": null
            },
            {
                "movie_id": 228,
                "title": "I Don't Like Younger Men",
                "release_date": "2017-01-01",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//bR1ID2VvQIHrWKdToWKc3mIpeyW.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//As12wwHuVa9Jtnd6XHX58RkzBFc.jpg",
                "overview": "Won-gi lost his wife a long time ago and is running a pension outside of the city. Then one day, Won-gi's daughter and her friend Se-yeong stays in the pension during a break from their school in Seoul. However, Won-gi finds himself attracted to the friend who is so much like his dead wife. Then he crosses a line that he shouldn't have crossed...",
                "creation_date": null
            },
            {
                "movie_id": 225,
                "title": "The Twilight Saga: Eclipse",
                "release_date": "2010-06-23",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//3mFM80dPzSqoXXuC2UMvLIRWX32.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//r4OqScx7hVXsG1obaJjJKJNaxHT.jpg",
                "overview": "Bella once again finds herself surrounded by danger as Seattle is ravaged by a string of mysterious killings and a malicious vampire continues her quest for revenge. In the midst of it all, she is forced to choose between her love for Edward and her friendship with Jacob, knowing that her decision has the potential to ignite the ageless struggle between vampire and werewolf. With her graduation quickly approaching, Bella is confronted with the most important decision of her life.",
                "creation_date": null
            },
            {
                "movie_id": 90,
                "title": "The Valet",
                "release_date": "2022-05-11",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//ba3oFhz6DkzSjVXsr50AGRMkfh8.jpg",
                "overview": "World famous movie star Olivia faces a PR disaster when a paparazzi snaps a photo of her with her married lover, Vincent. The hard-working valet Antonio accidentally appears in the same photo and is enlisted to pose as Olivia’s new boyfriend as a cover-up. This ruse with Olivia thrusts Antonio into the spotlight and unexpected chaos.",
                "creation_date": null
            },
            {
                "movie_id": 220,
                "title": "The In Between",
                "release_date": "2022-02-11",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//7RcyjraM1cB1Uxy2W9ZWrab4KCw.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//i9rEpTqC6aIQOWOc4PDEEAE3hFe.jpg",
                "overview": "After surviving a car accident that took the life of her boyfriend, a teenage girl believes he's attempting to reconnect with her from the after world.",
                "creation_date": null
            },
            {
                "movie_id": 92,
                "title": "After We Fell",
                "release_date": "2021-09-01",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//dU4HfnTEJDf9KvxGS9hgO7BVeju.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//lV3UFPPxDIPelh46G9oySXN9Mcz.jpg",
                "overview": "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
                "creation_date": null
            },
            {
                "movie_id": 223,
                "title": "Dark Spell",
                "release_date": "2021-02-11",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//2AbGdSGlU6CpiV3lswHUgE5CdAA.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//o2OSpKzXuB1edCDyVC2MXAxXwyJ.jpg",
                "overview": "Terror strikes when a heartbroken woman uses black magic to get her husband back.",
                "creation_date": null
            },
            {
                "movie_id": 93,
                "title": "Black Emanuelle",
                "release_date": "1975-11-27",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//hFlfmv5oOLxmbybo2ruX7B9b514.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//6DFL2MGl4SC2NvjlAbpl5C8WxtB.jpg",
                "overview": "In her first onscreen adventure, journalist/photographer Mae Jordan (known to her readers as \"Emanuelle\") travels to Africa on assignment. Questions of her own racial and sexual identity come to a head as she observes the troubled marriage of her hosts, Ann and Gianni Danieli. Matters are complicated further when Emanuelle finds herself in affairs with both of them, after which she flees Africa, only to be persued by Gianni, who had earlier rejected her and ridiculed her advances.",
                "creation_date": null
            },
            {
                "movie_id": 219,
                "title": "After We Collided",
                "release_date": "2020-09-02",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//kiX7UYfOpYrMFSAGbI6j1pFkLzQ.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//6hgItrYQEG33y0I7yP2SRl2ei4w.jpg",
                "overview": "Tessa finds herself struggling with her complicated relationship with Hardin; she faces a dilemma that could change their lives forever.",
                "creation_date": null
            },
            {
                "movie_id": 221,
                "title": "Redeeming Love",
                "release_date": "2022-01-21",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//z8VpsTdIjBhdeGeNEsHFwz6MJXp.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//lD8dFIk9wDEvOwZw0RB47e346io.jpg",
                "overview": "A retelling of the biblical book of Hosea set against the backdrop of the California Gold Rush of 1850.",
                "creation_date": null
            },
            {
                "movie_id": 227,
                "title": "Three Steps Above Heaven",
                "release_date": "2010-12-03",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//fcFz2xEZodKOxHDn9DazxPYHDSc.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//2Mq10FWFbxoYgsZysWlw7T9wSNe.jpg",
                "overview": "Story of two young people who belong to different worlds. It is the chronicle of a love improbable, almost impossible but inevitable dragging in a frantic journey they discover the first great love. Babi is a girl from upper-middle class that is educated in goodness and innocence . Hache is a rebellious boy, impulsive, unconscious, has a appetite for risk and danger embodied in endless fights and illegal motorbike races, the limit of common sense",
                "creation_date": null
            },
            {
                "movie_id": 88,
                "title": "After Ever Happy",
                "release_date": "2022-08-24",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//vWLyXOFm1C3gnS8ksfqi7gwkijn.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//sS4MadD7pKMt251vKxdJo2YrkYP.jpg",
                "overview": "As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
                "creation_date": null
            },
            {
                "movie_id": 224,
                "title": "Beauty Salon: Special Service 3",
                "release_date": "2019-04-29",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//fMksaQrIVsFlVCLS8KQfLGZ5vgt.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//4yABbmwq7D0vsSmDVzpJbQdFGJW.jpg",
                "overview": "In a deserted salon, female hair designer Se-jeong quits, and the salon is at risk. Jeong-soo, the owner, takes measures to overcome this hardship! He hires special male designers with 'special services'. Lonely women in the neighborhood soon hear about this, and start swarming into the salon.",
                "creation_date": null
            },
            {
                "movie_id": 222,
                "title": "Don't Blame Karma!",
                "release_date": "2022-08-03",
                "author": "temp",
                "type": "Romance",
                "poster": "https://image.tmdb.org/t/p/original//7BtnZMhU4V8Mq33609UpWvLSHE3.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//darIboeiaqC6AGCYZMZGXPEkOWJ.jpg",
                "overview": "The travails of Sara, a frustrated fashion designer who blames karma for her bad luck. Fate will put her face to face with her sister, Lucy, who enjoys very different luck, and in a series of events and reunions that will lead her to make a radical decision.",
                "creation_date": null
            }
        ],
        "Comedy": [
            {
                "movie_id": 57,
                "title": "The Man from Toronto",
                "release_date": "2022-06-24",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//uTCfTibqtk4f90cC59bLPMOmsfc.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//iOFBH9KtjKMntbP2kheeOpMQTcC.jpg",
                "overview": "In a case of mistaken identity, the world’s deadliest assassin, known as the Man from Toronto, and a New York City screw-up are forced to team up after being confused for each other at an Airbnb.",
                "creation_date": null
            },
            {
                "movie_id": 61,
                "title": "Hotel Transylvania: Transformania",
                "release_date": "2022-02-25",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//m3Ys7UDzUzOyoPYKzp4GhKKokUr.jpg",
                "overview": "When Van Helsing's mysterious invention, the \"Monsterfication Ray,\" goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
                "creation_date": null
            },
            {
                "movie_id": 64,
                "title": "Sing 2",
                "release_date": "2021-12-01",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//6mJrgL7Mi13XjJeGYJFlD6UEVQw.jpg",
                "overview": "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
                "creation_date": null
            },
            {
                "movie_id": 55,
                "title": "Dog",
                "release_date": "2022-02-17",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//rkpLvPDe0ZE62buUS32exdNr7zD.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//t0mwKhUDa62hdhdKSsN4xMfhY5Z.jpg",
                "overview": "An army ranger and his dog embark on a road trip along the Pacific Coast Highway to attend a friend's funeral.",
                "creation_date": null
            },
            {
                "movie_id": 56,
                "title": "The Lost City",
                "release_date": "2022-03-24",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//neMZH82Stu91d3iqvLdNQfqPPyl.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//1Ds7xy7ILo8u2WWxdnkJth1jQVT.jpg",
                "overview": "Reclusive author Loretta Sage writes about exotic places in her popular adventure novels that feature a handsome cover model named Alan. While on tour promoting her new book with Alan, Loretta gets kidnapped by an eccentric billionaire who hopes she can lead him to the ancient city's lost treasure that featured in her latest story. Alan, determined to prove he can be a hero in real life and not just on the pages of her books, sets off to rescue her.",
                "creation_date": null
            },
            {
                "movie_id": 58,
                "title": "Valley of the Dead",
                "release_date": "2022-03-11",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//avokvOwhjVR9GgISsSSgb2A343G.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//h6XfgbzQEV4sitsIVY63pawLI0s.jpg",
                "overview": "They're soldiers on different sides of the war. But when the dead come back to life, the only side they want to be on is the one that survives.",
                "creation_date": null
            },
            {
                "movie_id": 54,
                "title": "Sonic the Hedgehog 2",
                "release_date": "2022-03-30",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
                "overview": "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
                "creation_date": null
            },
            {
                "movie_id": 68,
                "title": "The Boss Baby: Family Business",
                "release_date": "2021-07-01",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//kv2Qk9MKFFQo4WQPaYta599HkJP.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//yBov7O4eXDcBLDpZrOHZzFr8rIl.jpg",
                "overview": "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
                "creation_date": null
            },
            {
                "movie_id": 51,
                "title": "Z-O-M-B-I-E-S 3",
                "release_date": "2022-07-09",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//ug8X5UkgdvcZ0WW0WNo5p0F1NGn.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//wNQpfAZkySbinb93qVwWIWaot1x.jpg",
                "overview": "Zed and Addison are beginning their final year at Seabrook High in the town that’s become a safe haven for monsters and humans alike. Zed is anticipating an athletic scholarship that will make him the first Zombie to attend college, while Addison is gearing up for Seabrook’s first international cheer-off competition. Then suddenly, extraterrestrial beings appear around Seabrook, provoking something other than friendly competition.",
                "creation_date": null
            },
            {
                "movie_id": 52,
                "title": "Turning Red",
                "release_date": "2022-03-10",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
                "overview": "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
                "creation_date": null
            },
            {
                "movie_id": 67,
                "title": "The Ice Age Adventures of Buck Wild",
                "release_date": "2022-01-28",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//zzXFM4FKDG7l1ufrAkwQYv2xvnh.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//eG0oOQVsniPAuecPzDD1B1gnYWy.jpg",
                "overview": "The fearless one-eyed weasel Buck teams up with mischievous possum brothers Crash & Eddie as they head off on a new adventure into Buck's home: The Dinosaur World.",
                "creation_date": null
            },
            {
                "movie_id": 63,
                "title": "DC League of Super-Pets",
                "release_date": "2022-07-27",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//r7XifzvtezNt31ypvsmb6Oqxw49.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//7ef3yg5eCE6ZGKMsqUrfH8KdSMA.jpg",
                "overview": "When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.",
                "creation_date": null
            },
            {
                "movie_id": 69,
                "title": "Too Old for Fairy Tales",
                "release_date": "2022-03-18",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//mwT58VqFZyAeQbscfynxtroqaft.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//jq1OvQj3El8BxhUxKmfmJaL8CzA.jpg",
                "overview": "In Waldek's life, filled mainly with computer games, there is a real earthquake. During her absence, mum stays under the care of a crazy and unpredictable aunt, who introduces discipline that has been alien to him so far and imposes new duties. But although an extraordinary relative gives Waldek a real survival camp, the boy also receives the most valuable life lesson from her.",
                "creation_date": null
            },
            {
                "movie_id": 60,
                "title": "Not Okay",
                "release_date": "2022-07-29",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//x1q3FkqFHBkMeKnHiS6GYgdLvUs.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//bHTAaLCXnMTThs57mAbptjmOLX2.jpg",
                "overview": "An ambitious young woman, desperate for followers and fame, fakes a trip to Paris to up her social media presence. When a terrifying incident takes place in the real world and becomes part of her imaginary trip, her white lie becomes a moral quandary that offers her all the attention she’s wanted.",
                "creation_date": null
            },
            {
                "movie_id": 59,
                "title": "Encanto",
                "release_date": "2021-11-24",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
                "overview": "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
                "creation_date": null
            },
            {
                "movie_id": 65,
                "title": "Hustle",
                "release_date": "2022-06-03",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//xWic7kPq13oRxYjbGLApXCnc7pz.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//e42d0nmC4GZjXjHyPvCeNiXZhW4.jpg",
                "overview": "After discovering a once-in-a-lifetime player with a rocky past abroad, a down on his luck basketball scout takes it upon himself to bring the phenom to the States without his team's approval. Against the odds, they have one final shot to prove they have what it takes to make it in the NBA.",
                "creation_date": null
            },
            {
                "movie_id": 62,
                "title": "The Bad Guys",
                "release_date": "2022-03-17",
                "author": "temp",
                "type": "Comedy",
                "poster": "https://image.tmdb.org/t/p/original//7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//9IDJpHROaC0S1ZlIxrvzOcOX5yC.jpg",
                "overview": "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
                "creation_date": null
            }
        ],
        "Netflix Originals": [
            {
                "movie_id": 122,
                "title": "Wellington Paranormal",
                "release_date": "2018-07-11",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//eaGpAP4bKMjVlMIoGqKzMRJ2OIG.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//yj8lWif4xcQCMIwPqEhqroso9jv.jpg",
                "overview": "New Zealand's capital is a hotbed of supernatural activity... so Officers Minogue and O'Leary, who featured in the vampire documentary What We Do In The Shadows, take to the streets to investigate all manner of paranormal phenomena.",
                "creation_date": null
            },
            {
                "movie_id": 130,
                "title": "The Legendaries",
                "release_date": "2019-02-08",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//3Z68s7a63wtQyrFyeFvfwE3hvps.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//zqx64ACNW8dFeviWdBtEPgdLvOS.jpg",
                "overview": "The Legendaries are a team of warriors who must relive their childhood to make amends for their adult mistakes. United once, united forever. Based on the original French comic book series.",
                "creation_date": null
            },
            {
                "movie_id": 129,
                "title": "Celebrity Treasure Island",
                "release_date": "2019-08-18",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//2aqyNa682MJsGRXXVb7K5Ctwy8f.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//h0rxqReQDf9wGf6fvoC6NKyz3eA.jpg",
                "overview": "Kiwi stars face off in paradise for the chance to win money for their chosen charities. With eliminations each week until the final celebrities remain, it will be a treasure hunt to end all treasure hunts!",
                "creation_date": null
            },
            {
                "movie_id": 203,
                "title": "Jono & Ben: Good Sports",
                "release_date": "2021-09-09",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//zdQlF2TUl05ZYPc943nDDi3XQUZ.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//7NROkJ18iPcHICWaivPqSkQckmb.jpg",
                "overview": "Infamous comedy duo Jono & Ben are on the hunt for Aotearoa's most unique sports. From roller derby to chilli eating and speed cubing, our country is overflowing with unsung sporting heroes.",
                "creation_date": null
            },
            {
                "movie_id": 201,
                "title": "60 Seconds",
                "release_date": "2022-03-14",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//hwCdqtOGSj54EqKqUk32QX1RMJe.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//iltwEQpfh93d3RavQhS54b2tv61.jpg",
                "overview": "In a world that's faster, bigger and better than ever, every second counts! With talent from all over Aotearoa, do these hopefuls have what it takes to become famous in 60 seconds?",
                "creation_date": null
            },
            {
                "movie_id": 127,
                "title": "Have You Been Paying Attention?",
                "release_date": "2019-07-24",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//1ceRRw6LY6ZFEeECq1OtURfOgzw.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//12aIxKFP6zPjd50atWdudQJavDX.jpg",
                "overview": "New Zealand's best and brightest comedians showcase their current affairs prowess unpacking the hot topics of the week: politics, sports, pop culture news and international affairs to test just who’s been paying attention.",
                "creation_date": null
            },
            {
                "movie_id": 124,
                "title": "Taskmaster NZ",
                "release_date": "2020-10-21",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//kZLpf13KnAc8u78sy4BUpa4tkwR.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//aJP6btfYhzjccJZwlKOg4CBRqY.jpg",
                "overview": "Jeremy Wells reigns supreme alongside his royal assistant Paul Williams, in the highly anticipated local version of Taskmaster. They'll be putting Kiwi comedians through their paces in a series of bizarre, hilarious and ingenious tasks.",
                "creation_date": null
            },
            {
                "movie_id": 199,
                "title": "Lego Masters NZ",
                "release_date": "2022-05-09",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//4zwajOEJSmZU53FI0eXvxvS8yy2.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//n7UK4wK1gNS5sLktndzKmMsGIuz.jpg",
                "overview": "Teams of Kiwi master brick builders are put through their paces in the New Zealand version of the hugely popular reality challenge. Who will dream, create it, and win it?!",
                "creation_date": null
            },
            {
                "movie_id": 123,
                "title": "Go Girls",
                "release_date": "2009-02-19",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//ipu0i0heAaD8yOPBXqa3O2dY1CT.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//4N0LX4gTCWzbJ2iSUBr2h8EAaRP.jpg",
                "overview": "Amy, Britta and Cody are three young women suffering their quarter century crisis: 25 and what have they achieved? They make a vow that in one year they’ll each fulfill their ambition. Their mate-since-childhood Kevin, admires their pluck but, to be honest, since Amy, Britta and Cody are currently Tragically Poor; Tragically Unknown; and Tragically Single, he reckons it’s going to be a bit of an ask.",
                "creation_date": null
            },
            {
                "movie_id": 128,
                "title": "Vegas",
                "release_date": "2021-04-19",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//rcf0lknfnbPD6aT6iQeSmIE5szu.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//6r5ioLgouMiVVEoAD1h56z9oC7u.jpg",
                "overview": "A business owner is thrust into New Zealand's dark underbelly after a million-dollar drug deal goes wrong on a blood-stained night, setting off a chain of events between dangerous factions.",
                "creation_date": null
            },
            {
                "movie_id": 126,
                "title": "Creamerie",
                "release_date": "2021-04-19",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//vUJ3zb24i2iAbzL8lJcdMYaEqEk.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//26WoKacrxqNL4mkawUbeteqp2EM.jpg",
                "overview": "Creamerie is set in a post-apocalyptic future where a viral plague has wiped out 99% of men, and Earth has become a planet run by and for women. There’ll be plenty to laugh at when three Kiwi-Asian women running a dairy farm encounter – shock, horror – a man!",
                "creation_date": null
            },
            {
                "movie_id": 200,
                "title": "Renters",
                "release_date": "2011-12-13",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//9c2wpkA6m6u6HVowX7mNF6BotUR.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//8FArEwRPSUxb9pgbHyneWpo6apG.jpg",
                "overview": "You won't believe how some tenants treat other people's homes in this fly-on-the-wall series.",
                "creation_date": null
            },
            {
                "movie_id": 125,
                "title": "Shortland Street",
                "release_date": "1992-05-25",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//2m2W5m2UIuxv2EkgfMvEms0iAGq.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//8R2sq2uf1c2KjhslRiGrmimKGpO.jpg",
                "overview": "A fast-paced serial drama in an urban setting, this show explores the lives and loves of the patients and staff of a modern metropolitan hospital and contains a heady mix of medical crisis, human drama, comedy, romance and suspense.",
                "creation_date": null
            },
            {
                "movie_id": 202,
                "title": "The Bachelor New Zealand",
                "release_date": "2015-03-17",
                "author": "temp",
                "type": "Netflix Originals",
                "poster": "https://image.tmdb.org/t/p/original//yVPUYhcel5n2z46OAL8ZNrVGYq6.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//8qU5dn0DaJb6eKtGDzsPg8z1iWQ.jpg",
                "overview": "New Zealand version of the reality dating competition where a single bachelor dates multiple women over several weeks, narrowing them down to hopefully find his true love.",
                "creation_date": null
            }
        ],
        "Documentaries": [
            {
                "movie_id": 106,
                "title": "Harry Potter 20th Anniversary: Return to Hogwarts",
                "release_date": "2022-01-01",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//8rft8A9nH43IReybFtYt21ezfMK.jpg",
                "overview": "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
                "creation_date": null
            },
            {
                "movie_id": 104,
                "title": "Beyond Infinity: Buzz and the Journey to Lightyear",
                "release_date": "2022-06-10",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//mnp0INIjyWt4AziWmTHgPk9IFoE.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//mBJ995JUssgh2hhm4JxNj8hyVVM.jpg",
                "overview": "Explore the evolution of Buzz Lightyear from toy to human in the making of Pixar’s Lightyear. Dive into the origin and cultural impact of everyone’s favorite Space Ranger, the art of designing a new “human Buzz,” and the challenges faced by the Lightyear crew along the way.",
                "creation_date": null
            },
            {
                "movie_id": 110,
                "title": "Naruto to Boruto: The Live 2019",
                "release_date": "2019-05-05",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//8OkxtHotJnegiBbWQSz8fD60NEc.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//eGa0w1EbNnb2wF696NVbF65IR4Y.jpg",
                "overview": "“NARUTO to BORUTO THE LIVE 2019”, a special event for the 20th anniversary of the first publication of “NARUTO” series in Weekly Shonen Jump!! Featuring live performances by artists performing the theme songs of both “NARUTO” and “BORUTO: NARUTO NEXT GENERATIONS”, anime cast members reading original story episodes, and more.",
                "creation_date": null
            },
            {
                "movie_id": 116,
                "title": "Russia's Wild Tiger",
                "release_date": "2022-01-30",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//32r7n0NgFAoV8Xepg0aYz46VYd6.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//mYSU5nCYVfUBh51TGu7V5fW6XXd.jpg",
                "overview": "Records the battle for the survival of the big cats and reveals intimate details of their lives. The animals they prey on are also in the film: tigers couldn’t survive without sika deer, Altai wapiti, wild boars and Asian black bears. Guiding the viewer through the film, an elder tiger tells the story of his cub, born in a conservation area, the year after he leaves his mother.",
                "creation_date": null
            },
            {
                "movie_id": 107,
                "title": "Jackass Forever",
                "release_date": "2022-02-01",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//ugIdyvtAzHWOguD91UjHKoAvfum.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//f2J8DpT5bqV0AiI9VVcfiuqKo5l.jpg",
                "overview": "Celebrate the joy of a perfectly executed shot to the groin as Johnny Knoxville, Steve-O and the rest of the gang return alongside some newcomers for one final round of hilarious, wildly absurd and often dangerous displays of stunts and comedy.",
                "creation_date": null
            },
            {
                "movie_id": 114,
                "title": "The Mystery of Marilyn Monroe: The Unheard Tapes",
                "release_date": "2022-04-27",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//9Ab3MEngH2sWK8uydGBFfgZDB4z.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//nXH3PbWtH7qpWlaAwFCvvh40pk8.jpg",
                "overview": "This documentary explores the mystery surrounding the death of movie icon Marilyn Monroe through previously unheard interviews with her inner circle.",
                "creation_date": null
            },
            {
                "movie_id": 115,
                "title": "My Daughter's Killer",
                "release_date": "2022-07-12",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//8apoud6p1sdd4oT8a6nYCzGpi6R.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//wxzaMHdRTUHllGjIvEqRJ3iAs8J.jpg",
                "overview": "A father fights for decades to bring his daughter's killer to justice in France and Germany before taking extreme measures.",
                "creation_date": null
            },
            {
                "movie_id": 109,
                "title": "Jennifer Lopez:  Halftime",
                "release_date": "2022-06-08",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//mPdZnmpdNYdMcMEAqUaJd4OdXHL.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//sVUj3GZ6qWCyaVyu4PpMlyYQbxd.jpg",
                "overview": "Global superstar Jennifer Lopez reflects on her multifaceted career and the pressure of life in the spotlight in this intimate documentary.",
                "creation_date": null
            },
            {
                "movie_id": 108,
                "title": "Girl in the Picture",
                "release_date": "2022-07-06",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//w6dnirDUhvWuHy91QECqGSYmOpa.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//uv1fvCclsZDL7nHjn5DVV7pdE6y.jpg",
                "overview": "A young mother’s mysterious death and her son’s subsequent kidnapping blow open a decades-long mystery about the woman’s true identity, and the murderous federal fugitive at the center of it all.",
                "creation_date": null
            },
            {
                "movie_id": 112,
                "title": "Cyber Hell: Exposing an Internet Horror",
                "release_date": "2022-05-17",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//eRlW6yvXHyXPuN0Ea6u6Sc48lGm.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//okUGREWC4LN2TSjFX0AOiNJhzdN.jpg",
                "overview": "Anonymous and exploitative, a network of online chat rooms ran rampant with sex crimes. The hunt to take down its operators required guts and tenacity.",
                "creation_date": null
            },
            {
                "movie_id": 118,
                "title": "50 Greatest Harry Potter Moments",
                "release_date": "2011-07-27",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//g1xiBoLD6v3ZaXPa4QtuXiQeYKW.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//4LOxoeZWt5wr9mooxEZRFK96lDd.jpg",
                "overview": "To mark the release two weeks ago of the eighth and final movie in the series, Robbie Coltrane narrates a countdown of the movie franchise's best moments. From Harry's first meeting with Ron and Hermione aboard the Hogwarts Express through to magical mysteries.",
                "creation_date": null
            },
            {
                "movie_id": 111,
                "title": "Porn to Be Free",
                "release_date": "2016-06-24",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//xhB2hGJBSvK69ZDOZJvNnoGh9vL.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//slh9qCbyDcMN2rC9FiueZ6pR2fj.jpg",
                "overview": "Italy, 1970. An increasing legion of harmless warriors begins a peaceful struggle for sexual freedom through pornography, shaking and shocking religious authorities and conservative political institutions. They are ironic, happy, crazy. They are dreamers, defenders of definitive communion between body and soul. But they were censored and humiliated. They were mistreated and arrested for demanding loud a new cultural renaissance.",
                "creation_date": null
            },
            {
                "movie_id": 117,
                "title": "Héctor El Father: Conocerás la verdad",
                "release_date": "2018-03-22",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//tkP0FzEivLxsUYt8BlaL8Sh7ceY.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//chKGRT7RjkHWlU0hRFQeJMx2Bra.jpg",
                "overview": "This autobiography of Hector Delgado runs from his childhood to become one of the greatest exponents of the urban genre, but the results of that life did not please him and led him to try to take his life  .After being victim of a firefight at a service station in Aguada, a city hall in Puerto Rico, he stopped earning at least two hundred American dollars for presentation and being \"devout of Jesus\"",
                "creation_date": null
            },
            {
                "movie_id": 121,
                "title": "Endangered",
                "release_date": "2022-06-12",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//6xsHWDAclu04VSsN19Dk6EMJMsQ.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//pTxBbyGLT2L7nGAMUcPHmzkGTUC.jpg",
                "overview": "A sobering look at the erosion of democracy & freedom of the press in the United States and abroad.",
                "creation_date": null
            },
            {
                "movie_id": 113,
                "title": "Jackass 4.5",
                "release_date": "2022-05-20",
                "author": "temp",
                "type": "Documentaries",
                "poster": "https://image.tmdb.org/t/p/original//bl686OSeMQOvs90IQAgt8QipCsB.jpg",
                "backdrop_poster": "https://image.tmdb.org/t/p/original//42975nYxawMHta0yoAtwm6ZPy0L.jpg",
                "overview": "Through outrageous, never-before-seen footage, witness the making of the Jackass crew's last go at wild stunts.",
                "creation_date": null
            }
        ]
    }
}